name: SignRanksPlus
main: com.empcraft.SignRanks
version: 0.1.6
commands:
   xpp:
      description: Transfer exp to another player.
      permission: signranks.xpp
   sr:
      description: Alias for /signranks
      permission: signranks.help
   signranks:
      description: Basic SignRanksPlus command.
      permission: signranks.help