name: SignRanksPlus
main: com.empcraft.SignRanks
version: 0.6.7
author: Empire92
website: www.empcraft.com
softdepend: [InSigns]
depend: [Vault]
commands:
   if:
      description: returns false or false depending on inputs (turn debug on if you want a message)
   execute:
      description: executes a function
   eval:
      description: evaluates an input (turn debug on if you want a message)
   else:
      description: basic else statement
   endif:
      description: basic end if statement
   gvar:
      description: manage global variables
   xpp:
      description: Transfer exp to another player. 
   sr:
      description: Alias for /signranks
   se:
      description: edit a sign
   signedit:
      description: edit a sign
   sedit:
      description: edit a sign
   schedule:
      description: schedule a task
   signranks:
      description: Basic SignRanksPlus command.
   all:
      description: Broadcasts a message (supports formatting)
   player:
      description: Displays text to a player (supports formatting)